### ISSUE TITLE
noarch guidance

### ISSUE THREAD

**Issue by notestaff** [bioconda/bioconda.github.io#25]
Bioconda recipe guidelines say not to use noarch ( https://bioconda.github.io/guidelines.html ); but many recipes do.  What is the current guidance?  @bioconda/core

**Comment by epruesse** [comment]
Use it. The docs need to be updated. Using `noarch` had been problematic pre CB3.

**Comment by bgruening** [comment]
@notestaff if you have time please also update the docs. Thanks.
